### ISSUE TITLE
Error on Inbound routing entry create on BMv2; P4

### ISSUE THREAD

**Issue by aputriax** [sonic-net/DASH#345]
There is an error on inbound routing create on BMv2:
**[bmv2] [E] [thread 15] [P4Runtime] Invalid match type**

This behavior is introduced by PR #194. 
And after a closer look at this PR we found one more issue:
 In the pipeline, inbound_routing is applied right after choosing a direction with direction_lookup. We don’t have any ENI associated with the packet at this stage. And the packet eventually would be dropped, no matter what we configured.

In the main branch all inbound related tests are disabled. So I've created a branch for reproducing this issue. It contains a single extra test module - `DASH/test/test-cases/functional/ptf/saidasheni_in.py`. Here is [the link](https://github.com/reshmaintel/DASH/tree/inbound_routing_issue_verification_2). Use [standard procedure](https://github.com/Azure/DASH/tree/main/dash-pipeline#i-feel-lucky) to run the tests. But instead of make run-all-tests do the following:
```
make run-saithrift-client-bash
cd functional/ptf
ptf --test-dir . --pypath /SAI/ptf --interface 0@veth1 --interface 1@veth3 saidasheni_in
```

In the switch tab you'll see the error I mentioned:
`[04:57:51.621] [bmv2] [E] [thread 17] [P4Runtime] Invalid match type`

NOTE: This issue is opened as a follow up for the Issue #233

**Comment by chrispsommers** [comment]
@marian-pritsak Can you provide an explanation for this error and is there a work item or potential remedy? it breaks test cases and we have to skip them. Thanks.

**Comment by chrispsommers** [comment]
@marian-pritsak Didn't you fix this in a PR?

**Comment by KrisNey-MSFT** [comment]
Discuss w/Community whether this is still a problem.  Originally from PLVision; @ashutosh-agrawal do you guys still want to own this Issue?

**Comment by ashutosh-agrawal** [comment]
@KrisNey-MSFT I'll take a look at this issue in the next couple of days and will get back to you.

**Comment by KrisNey-MSFT** [comment]
> @KrisNey-MSFT I'll take a look at this issue in the next couple of days and will get back to you.

thank you!

**Comment by KrisNey-MSFT** [comment]
still needed; bug in P4 code

**Comment by ashutosh-agrawal** [comment]
I ran this test yesterday and the P4 issue is fixed but the test is still failing. I fixed some initial issues, but it needs further debugging. @KrisNey-MSFT You can assign this issue to me.

**Comment by ashutosh-agrawal** [comment]
Opened this [PR](https://github.com/sonic-net/DASH/pull/534) that fixes the issue with programming of inbound routing table.

**Comment by KrisNey-MSFT** [comment]
> Opened this [PR](https://github.com/sonic-net/DASH/pull/534) that fixes the issue with programming of inbound routing table.

So ok to close this one @ashutosh-agrawal  ?

**Comment by ashutosh-agrawal** [comment]
My PR #534 fixed this issue for tests in saidasheni.py and PR #545 will take of remaining tests in saidashvnet.py. I think we can close it.
