### ISSUE TITLE
P4 `@name` annotations contain perhaps-unsupported characters

### ISSUE THREAD

**Issue by jafingerhut** [sonic-net/DASH#347]
It is not clear to me yet, but perhaps open source p4c and/or its P4Runtime API implementation might not support characters in `@name` annotations that are not legal P4 identifiers.  For example, it might not support the `|` character in this annotation: https://github.com/sonic-net/DASH/blob/611a15f50205979ed6f7d8679b7f48a399acb3ec/dash-pipeline/bmv2/dash_pipeline.p4#L201

See this p4c issue where @fruffy has been facing difficulties in this area: https://github.com/p4lang/p4c/pull/3885

**Comment by chrispsommers** [comment]
Hi Andy, @marian-pritsak would have more to say on this, but so far I am not aware of any problems resulting from the current DASH annotations. Also be aware that there is/was work underway to address https://github.com/sonic-net/DASH/issues/276 by adding custom annotations to direct the SAI code generator and remove the `@name(x|y)` approach.

**Comment by fruffy** [comment]
Thanks for opening this issue @jafingerhut. Yes, this issue is largely internal and will only become a problem when the IR is serialized into `.p4` or `.json` file.

**Comment by r12f** [comment]
ok, with the latest updates in DASH, all usage of "|" or ":" in the name are removed. we should not have this issue anymore. @jafingerhut and @fruffy do you have any other concerns on the name?

**Comment by fruffy** [comment]
Yes, we also fixed this problem with a couple compiler fixes for the inlining pass. Thanks for keeping track of this!

**Comment by r12f** [comment]
Np at all! I guess we can finally get this long running issue closed! 🎉

**Comment by KrisNey-MSFT** [comment]
Closing per thread
