### ISSUE TITLE
Update metadata (automatically) in SAI-Challenger to handle new attributes

### ISSUE THREAD

**Issue by chrispsommers** [sonic-net/DASH#374]
Copied from https://github.com/sonic-net/DASH/pull/365#issuecomment-1559030778 to ensure tracking:

Metadata is missing in SAI-C because the headers are generated automatically.
Here is visible what information is missing: https://github.com/taras-keryk-plv/SAI-Challenger/pull/81/files

**Comment by chrispsommers** [comment]
@andriy-kokhan Did we cover this already in SAI-C updates?

**Comment by andriy-kokhan** [comment]
> @andriy-kokhan Did we cover this already in SAI-C updates?

That's correct. This can be closed now. Thank you for tracking this!

**Comment by chrispsommers** [comment]
Fixed in https://github.com/sonic-net/DASH/pull/377 and https://github.com/sonic-net/DASH/pull/378
