### ISSUE TITLE
Q: P4 bmv2 pipeline source code change

### ISSUE THREAD

**Issue by KrisNey-MSFT** [sonic-net/DASH#382]
In the inbound case, Inbound Routing Table is using VNI, ENI and src_ip as search keys while **ENI is not defined yet**. The ENI is searched after this table later using a MAC address. I understand the Inbound routing table uses Underlay header while MAC to ENI table uses overlay header, but still it's not possible to use a key as a search field which is not defined yet.  Would you be able to help us understand?  thank you...

**Inbound_routing table:**

![image](https://github.com/sonic-net/DASH/assets/22226040/8fb2b597-b9b0-4349-a0a2-ee0c354e0372)

**Ether to ENI table**

![image](https://github.com/sonic-net/DASH/assets/22226040/b6cbd087-2ef1-4e64-a812-e8056811de5c)

**dash_pipeline.p4 code flow**

![image](https://github.com/sonic-net/DASH/assets/22226040/23f5b6e4-9690-450e-8ae6-7fe6cc834a58)

@saad-mzhr

**Comment by chrispsommers** [comment]
@marian-pritsak accepted task to fix this in WG meeting today

**Comment by KrisNey-MSFT** [comment]
PR396 should fix this [FIX](https://github.com/sonic-net/DASH/pull/396)

**Comment by chrispsommers** [comment]
Fixed in https://github.com/sonic-net/DASH/pull/396
