### ISSUE TITLE
Add Meter Policy Scale into documentation

### ISSUE THREAD

**Issue by KrisNey-MSFT** [sonic-net/DASH#387]
Per Community conversation, we would like to add the Meter Policy Scale information into either the HLD or the sdn-features-packet-transforms document(s).

**Comment by kperumalbfn** [comment]
@KrisNey-MSFT Metering scale numbers are in the HLD

https://github.com/sonic-net/DASH/blob/main/documentation/general/dash-sonic-hld.md

4K/ENI

**Comment by KrisNey-MSFT** [comment]
Question was re: the meter policy table

**Comment by KrisNey-MSFT** [comment]
Closing, question answered
