### ISSUE TITLE
SAI move to Master (Intel)

### ISSUE THREAD

**Issue by KrisNey-MSFT** [sonic-net/DASH#388]
SAI needs to be moved to Master; this is still being worked at Intel.  
An OCP SAI fix is needed and from there they can move the pointer, which is needed for DASH (for VXLAN).  
(request from Vincent)

**Comment by KrisNey-MSFT** [comment]
https://github.com/opencomputeproject/SAI/pull/1755/files

https://github.com/opencomputeproject/SAI/pull/1573

Sent email to @richardyu-ms internally

**Comment by KrisNey-MSFT** [comment]
Need to move pointer from DASH to SAI instead of the private fork, @reshmaintel will do this.

**Comment by ravi861** [comment]
https://github.com/sonic-net/DASH/pull/398 should resolve this issue.

**Comment by KrisNey-MSFT** [comment]
hi guys, sorry I'm late on this one... is it okay to close?  
@kcudnik @reshmaintel

**Comment by chrispsommers** [comment]
Yup, we've moved to master twice since this was opened, just this morning it was updated again by @kcudnik and I merged it.
