### ISSUE TITLE
Meter questions: Vincent

### ISSUE THREAD

**Issue by KrisNey-MSFT** [sonic-net/DASH#390]
Placeholder for Vincent to add Metering questions:

Routes and Mappings have meters.  Meter policy result comes in.  If we do not have mapping overriding meter class, we end up trying to find a bucket on the ENI for the meter class.   Vincent to add question here...

**Comment by vincent-xs** [comment]
before metering was introduced, we have the following counters defined in SAI:
ACL rule (for match), outbound route and mapping.

metering expanded the outbound route and mapping with a 16 bit meter class (and flags). a policy based meter class was also added at the ENI level. Metering defines then a certain logic to get the proper meter class "computed" and then the associated bucket on the current ENI to be updated. this metering logic is clear.

Also, counters are defined https://github.com/sonic-net/DASH/blob/main/documentation/general/sdn-features-packet-transforms.md#counters
I believe some of that section describes metering (aka billing).
I also believe the table describes "fixed" per ENI stats that we just don't have SAI for.

1. what happens to the outbound route and mapping counters? do they remain in addition to the metering class itself? 
2. if they remain, what is the scale of those counters.
3. what is the scale of the ACL match counter (assuming this is also an optional counter)
4. for ENI based counters: are the meter class buckets completely separated from the fixed counters that are assumed to be on ENI? 

if everything remains the same, I believe that on outbound, we would increment the following counters
outbound route counter (optional)
outbound map counter (optional)
ENI counters (packet, byte, unicast, mcast, etc...)  (always present)
ENI based bucket counter based on the resulting meter class (if any) (optional)

**Comment by KrisNey-MSFT** [comment]
Adding @vincent-xs

**Comment by KrisNey-MSFT** [comment]
@prsunny for offline

**Comment by prsunny** [comment]
@vijasrin , can you help with the questions?

**Comment by vijasrin** [comment]
> 4. for ENI based counters: are the meter class buckets completely separated from the fixed counters that are assumed to be on ENI?

Yes, meter class buckets are separated from the per ENI counters. Metering bucket counters per ENI are optional and used to account for differnet classes of traffic for billing purposes only

> 
> as talked about in the meeting, could we also document the fact that 1/ the meter_class (16bit) value of 0 is reserved as "metering" disabled (this would allow un-setting the meter class on the route 2/ once a meter policy is applied to an ENI, its rule set cannot be modified (same behavior as Acl group)

okay. will clarify and update the hld

**Comment by vincent-xs** [comment]
still need clarification on Metering vs regular accounting 1.->3.

1. what happens to the outbound route and mapping counters? do they remain in addition to the metering class itself?

1. if they remain, what is the scale of those counters.

1. what is the scale of the ACL match counter (assuming this is also an optional counter)

**Comment by KrisNey-MSFT** [comment]
Adding @r12f and @kperumalbfn to assist @prsunny

**Comment by KrisNey-MSFT** [comment]
@r12f  @kperumalbfn @prsunny or @vijasrin 
Would it be possible to respond here before the meeting on Wednesday?

**Comment by kperumalbfn** [comment]
@vincent-xs For these optional counters, is it possible to have a flex counter block that can be attached to few route/mapping/ACL table entries? For eg: counters can be attached to drop entries in these blocks and that will be useful for debugging.

**Comment by KrisNey-MSFT** [comment]
Sirius has no per route or per mapping counters because of the scale.  
Is this moving into a Counters discussion?  
@vincent-xs will cross reference w/HLD and Packet Transforms Doc

https://github.com/sonic-net/DASH/blob/main/documentation/general/sdn-features-packet-transforms.md#counters

**Comment by vincent-xs** [comment]
opened https://github.com/sonic-net/DASH/issues/417 for the remaining optional counters.

closing this issue, meter questions have been answered.
