### ISSUE TITLE
Calculation error in program scale testing requirements?

### ISSUE THREAD

**Issue by ashutosh-agrawal** [sonic-net/DASH#397]
My question is specifically on the line below. Not sure where 1000 came from? Based on the equation, it should be 5Mand the total flow table size would be ~40M.

Flow Table Size: (2 * CPS) + 15M + 15M //For 5M CPS, Flow Table Size: (2 * **1000**) + 15M + 15M = ~30M

https://github.com/sonic-net/DASH/blob/main/documentation/general/program-scale-testing-requirements-draft.md#:~:text=Flow%20Table%20Size%3A%20(2%20*%20CPS)%20%2B%2015M%20%2B%2015M%20//For%205M%20CPS%2C%20Flow%20Table%20Size%3A%20(2%20*%201000)%20%2B%2015M%20%2B%2015M%20%3D%20~30M

**Comment by KrisNey-MSFT** [comment]
1000 is # of CPS flows; at any given time there may be a few thousand flows in the table.  30M are fixed, 2,000 are being cycled w/open-close.  We _should_ never exceed 32M. 
@mgheorghe provided answers to @ashutosh-agrawal

**Comment by KrisNey-MSFT** [comment]
(2 * 1000) may be variable depending upon network latency delay - @mgheorghe will write a paragraph to clarify.

**Comment by KrisNey-MSFT** [comment]
Closing per convo w/ @mgheorghe
