### ISSUE TITLE
Proposal to move libsai.so utils.cpp constructor to sai_api_initialize() function

### ISSUE THREAD

**Issue by kcudnik** [sonic-net/DASH#411]
I think we should move grpc/p4 initialization inside sai_api_initialize() function:

https://github.com/sonic-net/DASH/blob/main/dash-pipeline/SAI/templates/utils.cpp.j2#L88

is there any specific reason why this needs to be held as constructor ? if we move that to api_initialize we then could pass easy parameters to initialize, like grpcTarget, pipeline json and p4rt txt

**Comment by kcudnik** [comment]
@marian-pritsak FYI

**Comment by lguohan** [comment]
lgtm

**Comment by chrispsommers** [comment]
Hi @kcudnik, @marian-pritsak wrote the constructor, but I am suspecting this is because there is no other caller of `sai_api_initialize()`, i.e. no syncd. In DASH we link `libsai.so` to `sai_rpc_server.cpp` (auto-generated saithrift server code) and AFAIK there is no call to `sai_api_initialize()`. Where, then, is the way to ensure such initialization is performed? That's why a constructor is needed. Perhaps you have some other specific suggestion? Thanks.

**Comment by kcudnik** [comment]
syncd is calling sai_api_initialize, and i think sai_rpc_server also could do that, if that's auto generated then i don't see the problem to add that line of call, i think passing arguments via it would be more beneficial, 

@chrispsommers i can make the change if you point me to the right code

**Comment by chrispsommers** [comment]
Hi @kcudnik I need to revise my comment. I did locate the call the `sai_api_initialize()`, it was in [saiserver.cpp](https://github.com/opencomputeproject/SAI/blob/master/test/saithriftv2/src/saiserver.cpp#L278). So I guess we should ask Marian why he chose not to initialize here.

I will hazard one more guess: when Marian first developed libsai for DASH there was no saithriift server, there was only a simple test main program https://github.com/sonic-net/DASH/blob/main/dash-pipeline/tests/libsai/vnet_out/vnet_out.cpp which I suppose could have called `sai_api_initialize()` but did not. Instead the init constructor was used. I added saithrift server support later and left things as-is.

I'd like to hear @marian-pritsak's opinion. But as far as I am concerned, if you wish to refactor things to do it like you propose, go ahead. Just ensure the two simple test programs under https://github.com/sonic-net/DASH/tree/main/dash-pipeline/tests/libsai get the requisite calls to `sai_api_initialize()` and all CI/CD tests continue to work.

Thanks for the suggestions!

**Comment by kcudnik** [comment]
thats sound good, lets hear from @marian-pritsak, i will be refactoring libsai.so in this repo, to make it more friendly when using with syncd, and i will need make thinks more useful, i already started to add missing apis here: https://github.com/sonic-net/DASH/pull/410

**Comment by chrispsommers** [comment]
Thanks @kcudnik I have noticed your changes, your help is very welcome here! I suspect @vincent-xs will find this of interest as well.

**Comment by kcudnik** [comment]
I can add you all to my future PRs

**Comment by chrispsommers** [comment]
> btw. are those 2 programs used in test pipeline in github ? or they are just standalone ?

They are called as part of CI pipeline: https://github.com/sonic-net/DASH/blob/main/.github/workflows/dash-bmv2-ci.yml#L74

The actual scope of the "libsai test" is very small, but I hate to discard it because they're the only c-level tests we have. In an ideal world with more unit testing, it should be more extensive. However, there are a lot of functional tests using saithrift so at least we have that coverage.

**Comment by kcudnik** [comment]
that's good, so in sairedis syncd we don't want to go via sai-thrift, we want directly link to libsai.so so, i will be working on that as well as setting environment for that to work, i have a lot to unwrap from those makefiles here :)

**Comment by chrispsommers** [comment]
@kcudnik Please feel free to consult me regarding all the build processes under dash-pipeline, including Makefiles, Dockerfiles, etc. I was a major contributor to that. Please see the READMEs there as well, I tried to explain a lot, but there is always room for improvement and another point of view. If you ever want a 1:1 mtg to discuss something or get an orientation, I am open to that as well. Reach out to me at chris.sommers@keysight.com.

**Comment by kcudnik** [comment]
> @kcudnik Please feel free to consult me regarding all the build processes under dash-pipeline, including Makefiles, Dockerfiles, etc. I was a major contributor to that. Please see the READMEs there as well, I tried to explain a lot, but there is always room for improvement and another point of view. If you ever want a 1:1 mtg to discuss something or get an orientation, I am open to that as well. Reach out to me at [chris.sommers@keysight.com](mailto:chris.sommers@keysight.com).

thanks, i will keep this in mind, if i will need any help will defenetly ping you.

btw. our goal is to make libsai.so which could be linked inside syncd docker in sonic, as well as p4/bmv2 simulator docker will need to be setup along with this in separate docker as im aware right now, future more since bmv2 only supports dash functionality, we plan to merge dash sai implementation with virtual switch (very long term goal) in sonic buildimage to have a virtual asic that supports base SAI api (non dash) and dash apis under 1 layer, and later on make and support test env for virtual device for people to use

**Comment by chrispsommers** [comment]
Fixed by https://github.com/sonic-net/DASH/issues/411
