### ISSUE TITLE
[SAI] wrong code generated in libsai

### ISSUE THREAD

**Issue by kcudnik** [sonic-net/DASH#415]
I found some issues with generated code for libsai.so from templates after enabling compiler warnings:

```
saidashvip.cpp
saidashacl.cpp: In function 'sai_status_t sai_create_dash_acl_group(sai_object_id_t*, sai_object_id_t, uint32_t, const sai_attribute_t*)':
saidashacl.cpp:39:15: warning: conversion from 'sai_object_id_t' {aka 'long unsigned int'} to 'sai_uint16_t' {aka 'short unsigned int'} may change value [-Wconversion]
   39 |     u16SetVal(objId, mf_exact, 16);
      |               ^~~~~
saidasheni.cpp: In function 'sai_status_t sai_create_eni(sai_object_id_t*, sai_object_id_t, uint32_t, const sai_attribute_t*)':
saidasheni.cpp:200:15: warning: conversion from 'sai_object_id_t' {aka 'long unsigned int'} to 'sai_uint16_t' {aka 'short unsigned int'} may change value [-Wconversion]
  200 |     u16SetVal(objId, mf_exact, 16);
      |               ^~~~~
saidashinboundrouting.cpp: In function 'sai_status_t sai_create_inbound_routing_entry(const sai_inbound_routing_entry_t*, uint32_t, const sai_attribute_t*)':
saidashinboundrouting.cpp:27:31: warning: conversion from 'sai_object_id_t' {aka 'long unsigned int'} to 'sai_uint16_t' {aka 'short unsigned int'} may change value [-Wconversion]
   27 |         u16SetVal(tableEntry->eni_id, mf_exact, 16);
      |                   ~~~~~~~~~~~~^~~~~~
saidashinboundrouting.cpp: In function 'sai_status_t sai_remove_inbound_routing_entry(const sai_inbound_routing_entry_t*)':
saidashinboundrouting.cpp:131:31: warning: conversion from 'sai_object_id_t' {aka 'long unsigned int'} to 'sai_uint16_t' {aka 'short unsigned int'} may change value [-Wconversion]
  131 |         u16SetVal(tableEntry->eni_id, mf_exact, 16);
      |                   ~~~~~~~~~~~~^~~~~~
saidashmeter.cpp: In function 'sai_status_t sai_create_meter_policy(sai_object_id_t*, sai_object_id_t, uint32_t, const sai_attribute_t*)':
saidashmeter.cpp:217:15: warning: conversion from 'sai_object_id_t' {aka 'long unsigned int'} to 'sai_uint16_t' {aka 'short unsigned int'} may change value [-Wconversion]
  217 |     u16SetVal(objId, mf_exact, 16);

...
saidashoutboundrouting.cpp:158:22: note: shadowed declaration is here
  158 |                 auto param = action->add_params();
      |                      ^~~~~
saidashoutboundrouting.cpp:178:26: warning: declaration of 'param' shadows a previous local [-Wshadow]
  178 |                     auto param = action->add_params();
      |                          ^~~~~
saidashoutboundrouting.cpp:172:22: note: shadowed declaration is here
  172 |                 auto param = action->add_params();
      |                      ^~~~~
saidashoutboundrouting.cpp:192:26: warning: declaration of 'param' shadows a previous local [-Wshadow]
  192 |                     auto param = action->add_params();
      |                          ^~~~~
saidashoutboundrouting.cpp:186:22: note: shadowed declaration is here
  186 |                 auto param = action->add_params();
      |                      ^~~~~
saidashoutboundrouting.cpp: In function 'sai_status_t sai_remove_outbound_routing_entry(const sai_outbound_routing_entry_t*)':
saidashoutboundrouting.cpp:275:31: warning: conversion from 'sai_object_id_t' {aka 'long unsigned int'} to 'sai_uint16_t' {aka 'short unsigned int'} may change value [-Wconversion]
  275 |         u16SetVal(tableEntry->eni_id, mf_exact, 16);
      |                   ~~~~~~~~~~~~^~~~~~
saidashvnet.cpp: In function 'sai_status_t sai_create_vnet(sai_object_id_t*, sai_object_id_t, uint32_t, const sai_attribute_t*)':
saidashvnet.cpp:39:15: warning: conversion from 'sai_object_id_t' {aka 'long unsigned int'} to 'sai_uint16_t' {aka 'short unsigned int'} may change value [-Wconversion]
   39 |     u16SetVal(objId, mf_exact, 16);
      |               ^~~~~
saidashpavalidation.cpp: In function 'sai_status_t sai_create_pa_validation_entry(const sai_pa_validation_entry_t*, uint32_t, const sai_attribute_t*)':
saidashpavalidation.cpp:27:31: warning: conversion from 'sai_object_id_t' {aka 'long unsigned int'} to 'sai_uint16_t' {aka 'short unsigned int'} may change value [-Wconversion]
   27 |         u16SetVal(tableEntry->vnet_id, mf_exact, 16);
      |                   ~~~~~~~~~~~~^~~~~~~
saidashpavalidation.cpp: In function 'sai_status_t sai_remove_pa_validation_entry(const sai_pa_validation_entry_t*)':
saidashpavalidation.cpp:105:31: warning: conversion from 'sai_object_id_t' {aka 'long unsigned int'} to 'sai_uint16_t' {aka 'short unsigned int'} may change value [-Wconversion]
  105 |         u16SetVal(tableEntry->vnet_id, mf_exact, 16);
      |   
```

there are 2 issues here:
1. param variable is shadowed 
2. u16SetVal(objId, mf_exact, 16); and u16SetVal(tableEntry->vnet_id passes uint64_t to uint16_t param, not sure what was intended here but this is an error (i don't know how to fix this, probably some new function needs to be added to utils.cpp)

@marian-pritsak @chrispsommers please take a look and advise how to fix or provide solution

**Comment by kcudnik** [comment]
After this will be fixed this https://github.com/sonic-net/DASH/pull/416/files#diff-0aa5719be28d4f17eb9bfe12e51198fadd9f7c1b0bf0a36600ffb345e7570d05R15 can be uncommented

**Comment by chrispsommers** [comment]
@marian-pritsak might be the best person to look at this, I think it was his code originally.

**Comment by kcudnik** [comment]
i fixed param shadow warning

**Comment by kcudnik** [comment]
ping

**Comment by kcudnik** [comment]
@marian-pritsak please advise how to fix those obj issues

**Comment by kcudnik** [comment]
ping

**Comment by KrisNey-MSFT** [comment]
Idea was possibly to generate a struct; truncate to lower 16 bits.  Will this cause an issue with a duplicate object name/id?

**Comment by kcudnik** [comment]
@marian-pritsak please help resolve that, or at least give hints how i can do it myself, i really like to enable warnings as errors in this repo

**Comment by kcudnik** [comment]
ping

**Comment by kcudnik** [comment]
ping

**Comment by chrispsommers** [comment]
Per @marian-pritsak needs some more work to find a better way to perform casting. Deferred for now, it's not "broken."

**Comment by kcudnik** [comment]
yea, thanks, not calming it's broken, just generates warnings during compilation, and i want to enable warnings as errors to eliminate this in the future

**Comment by kcudnik** [comment]
@marian-pritsak i has been 2 months on this, please take care of this, this is only 1 line of code which needs your attention, you alreade mentioned on DASH meetings to help with this

**Comment by KrisNey-MSFT** [comment]
check back next week

**Comment by KrisNey-MSFT** [comment]
check back next week

**Comment by KrisNey-MSFT** [comment]
@AmithGspn has offered to take a look, adding as Assigned

**Comment by KrisNey-MSFT** [comment]
From Meyappan:

Hi Chris,

Patch for issue#415. Compiled without warnings. Yet to test.   
Please check for any major gaps, will test and feedback next week.

diff --git a/dash-pipeline/SAI/SAI b/dash-pipeline/SAI/SAI 
--- a/dash-pipeline/SAI/SAI
+++ b/dash-pipeline/SAI/SAI
@@ -1 +1 @@
-Subproject commit 683d72720b3318f83c54074edfa501ea6812550d
+Subproject commit 683d72720b3318f83c54074edfa501ea6812550d-dirty
diff --git a/dash-pipeline/SAI/templates/saiapi.cpp.j2 b/dash-pipeline/SAI/templates/saiapi.cpp.j2
index 2ca9a35..cb919b3 100644
--- a/dash-pipeline/SAI/templates/saiapi.cpp.j2
+++ b/dash-pipeline/SAI/templates/saiapi.cpp.j2
@@ -61,7 +61,8 @@ static sai_status_t dash_sai_create_{{ table.name }}(
     auto mf = matchActionEntry->add_match();
     mf->set_field_id({{table['keys'][0].id}});
     auto mf_exact = mf->mutable_exact();
-    {{table['keys'][0].field}}SetVal(objId, mf_exact, {{table['keys'][0].bitwidth}});
+    //{{table['keys'][0].field}}SetVal(objId, mf_exact, {{table['keys'][0].bitwidth}});
+      {{table['keys'][0].field}}SetVal(static_cast<uint{{ table['keys'][0].bitwidth }}_t>(objId), mf_exact, {{ table['keys'][0].bitwidth }});
     {% else %}
     // SAI object table with multiple P4 table keys
     // Copy P4 table keys from appropriate SAI attributes
@@ -339,7 +340,14 @@ static sai_status_t dash_sai_create_{{ table.name }}(
         mf->set_field_id({{key.id}});
         {% if key.match_type == 'exact' %}
         auto mf_exact = mf->mutable_exact();
-        {{key.field}}SetVal(tableEntry->{{ key.sai_key_name | lower }}, mf_exact, {{key.bitwidth}});
+        //{{key.field}}SetVal(tableEntry->{{ key.sai_key_name | lower }}, mf_exact, {{key.bitwidth}});
+        {% set keyfield = key.field %}
+        {% set bitwidth = key.bitwidth %}
+        {% if keyfield in ['ipaddr'] or bitwidth in [24,48] %}
+          {{key.field}}SetVal(tableEntry->{{ key.sai_key_name | lower }}, mf_exact, {{key.bitwidth}});
+        {% else %}
+          {{key.field}}SetVal(static_cast<uint{{key.bitwidth}}_t>(tableEntry->{{ key.sai_key_name | lower }}), mf_exact, {{key.bitwidth}});
+        {% endif %}
         {% elif key.match_type == 'lpm' %}
         auto mf_lpm = mf->mutable_lpm();
         {{key.field}}SetVal(tableEntry->{{ key.sai_key_name | lower }}, mf_lpm, {{key.bitwidth}});
@@ -496,7 +504,14 @@ static sai_status_t dash_sai_remove_{{ table.name }}(
         mf->set_field_id({{key.id}});
         {% if key.match_type == 'exact' %}
         auto mf_exact = mf->mutable_exact();
-        {{key.field}}SetVal(tableEntry->{{ key.sai_key_name | lower }}, mf_exact, {{key.bitwidth}});
+        {% set keyfield = key.field %}
+        {% set bitwidth = key.bitwidth %}
+        {% if keyfield in ['ipaddr'] or bitwidth in [24,48] %}
+           {{key.field}}SetVal(tableEntry->{{ key.sai_key_name | lower }}, mf_exact, {{key.bitwidth}});
+        {% else %}
+          {{key.field}}SetVal(static_cast<uint{{key.bitwidth}}_t>(tableEntry->{{ key.sai_key_name | lower }}), mf_exact, {{key.bitwidth}});
+        {% endif %}
+        //{{key.field}}SetVal(tableEntry->{{ key.sai_key_name | lower }}, mf_exact, {{key.bitwidth}});
         {% elif key.match_type == 'lpm' %}
         auto mf_lpm = mf->mutable_lpm();
         {{key.field}}SetVal(tableEntry->{{ key.sai_key_name | lower }}, mf_lpm, {{key.bitwidth}});


Note:
Diwali vacation in India, will be back to work on Tuesday.

**Comment by KrisNey-MSFT** [comment]
Thanks for your contribution!
The best way to submit for review is to submit a pull request to DASH and tag folks for review. We don’t work with patch diffs. Yo can mark the PR “Draft” if you want until you’ve tested it. I can assign reviewers to the PR. If you write in the PR description “Fix <URL of filed issue>” It automatically creates cross-references which will alert anyone associated with the original issue. Please make sure you’ve given your Github ID to Kristina Moore.

You should be able to test in a few minutes using the workflow described in the READMEs:

make clean
make all
make run-switch
make run-saithrift-server
make run-all-tests

Also, when you push your fork to your own repo, it will run the CI pipeline and do all the building and testing automatically! Just make sure you have “enabled actions” in your fork, see image below. You should ensure everything passes before you submit any PR. When you do submit a PR, the CI actions will be run in the DASH repo proper and appear as PR “checks” status.

**Comment by kcudnik** [comment]
Can autor make a PR?

**Comment by chrispsommers** [comment]
Fixed by https://github.com/sonic-net/DASH/pull/463
