### ISSUE TITLE
what is a flow ?

### ISSUE THREAD

**Issue by mgheorghe** [sonic-net/DASH#424]
in dash we have a few supported protocols, UDP, TCP and ICMP

i see the word flow many times but i have not seen a dash definition of a flow.

so when we send a TCP connection  and we have the SYN and SYNACK, do we have 1 flow? or 2 flows ?
same question for UDP if i send 1 packet and i get a packet back (reverse IPs, reverse UDP ports..) is that 1 flow "a call" or it will be counted as 2 flows ?
same with ICMP echo request and then echo replay , is this 1 flow or 2 flows ?

asking this because i see implementations that count a tcp exchange as 1 flow and some as 2 flows. and will be good to standardize on dash when we say 32M flows what is a flow so everyone counts the same.

https://www.rfc-editor.org/rfc/rfc2722.html

```
For the purpose of traffic flow measurement we define the concept of
   a TRAFFIC FLOW, which is like an artificial logical equivalent to a
   call or connection.  A flow is a portion of traffic, delimited by a
   start and stop time, that belongs to one of the metered traffic
   groups mentioned above.  Attribute values (source/destination
   addresses, packet counts, byte counts, etc.)  associated with a flow
   are aggregate quantities reflecting events which take place in the
   DURATION between the start and stop times.  The start time of a flow
   is fixed for a given flow; the stop time may increase with the age of
   the flow.
```

https://www.rfc-editor.org/rfc/rfc3917

```
A flow is defined as a set of IP packets passing an observation point
   in the network during a certain time interval.  All packets belonging
   to a particular flow have a set of common properties.  Each property
   is defined as the result of applying a function to the values of:

      1. one or more packet header field (e.g., destination IP address),
         transport header field (e.g., destination port number), or
         application header field (e.g., RTP header fields [[RFC3550](https://www.rfc-editor.org/rfc/rfc3550)])

      2. one or more characteristics of the packet itself (e.g., number
         of MPLS labels, etc.)

      3. one or more of fields derived from packet treatment (e.g., next
         hop IP address, the output interface, etc.)
```

https://learn.microsoft.com/en-us/azure/virtual-network/virtual-machine-network-throughput

```
A typical TCP/UDP connection has two flows created, 
one for the inbound and another for the outbound direction. 
Each flow is distinguished by a 5-tuple 
(protocol, local IP address, remote IP address, local port, and remote port) information.
```

**Comment by KrisNey-MSFT** [comment]
@mgheorghe and @KrisNey-MSFT went over this w/ @GeraldatMicrosoft 
@mgheorghe to update if needed

**Comment by GeraldatMicrosoft** [comment]
Regardless of TCP or UDP we always setup a flow for inbound and outbound. Essentially we always setup bi-directionally even for UDP. So for example, if we say the connection table supports 32M connections it is actually 64M flows. Again, regardless of TCP/UDP.

**Comment by KrisNey-MSFT** [comment]
@mgheorghe - ok to close this one?
