### ISSUE TITLE
saiapi.j2 change causes for "create and set" flag to be changed

### ISSUE THREAD

**Issue by vincent-xs** [sonic-net/DASH#439]
@vijasrin 

part of this commit
Author: Vijay Srinivasan
Revision: add355e26b5ed5c86140a3559d851a5a9ae8b499
Date: 2023-06-21 12:44:23
Comment: Adding support for metering (#365)

- Metering P4 model changes in BMV2 
- Changes to support the SAI api generation for metering tables 
[See List of Changed Symbols](https://github.com/sonic-net/DASH/issues/expandTags(12))

modified
1/ saiapi.j2 logic for mandatory variables (affecting all vendor LIBSAI)
this is mostly this check:
{% for key in table['keys'] %}
{% if key.isattribute != 'false' %} <<<<<<<<<<<<<<<< is this check stating: this parameter is not part of any lookup key, so no need to make it mandatory ? (this would be the case for the VNI we get from VNET, that VNI being only used as packet data on outbound).

    /**
     * @brief {{ key.match_type | capitalize | replace('Lpm', 'LPM') }} matched key {{ key.sai_key_name }}
     *
     * @type {{ key.type }}
     * @flags MANDATORY_ON_CREATE | CREATE_ONLY
{% if key.type == 'sai_uint16_t' %}

2/ commented out in BMV2 the expected/match param logic (just BMV2 sai)

any reason for this?

**Comment by vijasrin** [comment]
@vincent-xs 
1. The key.isattribute was meant to be used in cases where table keys also needed to be past of the attribute enums. Looks like this is deprecated and being used anywhere. The removal of the if condition also generates the same output.

2. Ref: https://github.com/sonic-net/DASH/issues/370 optional attributes should not be required which was causing an assert. Hence this check was commented out in the bmv2 lisai
