### ISSUE TITLE
SAI generation for ternary key leads to all fields be mandatory on create

### ISSUE THREAD

**Issue by vincent-xs** [sonic-net/DASH#440]
while syncing the mandatory expectations of our libsai against the SAI header MANDATORY_ON_CREATE flag, I noticed that all key fields for ACL rules are mandatory.

since ACL rules are typically filtering on a subsets of fields, it is strange to make them all mandatory

note: the SAI header generation was done setting DASH_MATCH for the dash_acl.p4 compile (since that's the expected official SAI API).

**Comment by KrisNey-MSFT** [comment]
Answered this week during Community Call.
