### ISSUE TITLE
SAI API meter flags not mandatory on meter class

### ISSUE THREAD

**Issue by vincent-xs** [sonic-net/DASH#441]
@vijasrin 

shouldn't the meter class of a meter rule be a mandatory parameter?

    /**
     * @brief Action set_policy_meter_class parameter METER_CLASS
     *
     * @type sai_uint16_t
     * @flags CREATE_AND_SET
     * @isvlan false
     * @default 0
     */
    SAI_METER_RULE_ATTR_METER_CLASS,

**Comment by KrisNey-MSFT** [comment]
Should this be mandatory on create?  
@vijasrin to take a look

**Comment by vijasrin** [comment]
This is not a strictly mandatory attribute since the meter class has a default value of 0. Although unlikely, it should be okay to not specify a meter class since there is a fallback to the default value.

**Comment by KrisNey-MSFT** [comment]
Answered and ok to close per Community discussion.

**Comment by vincent-xs** [comment]
this makes sense, given the default definition.
Tahnks Vijay.
closing the issue
