### ISSUE TITLE
10.1.2.5 does not exist in sample but is mentioned in the description

### ISSUE THREAD

**Issue by mgheorghe** [sonic-net/DASH#452]
https://github.com/sonic-net/DASH/blob/main/documentation/general/dash-sonic-hld.md

but the vnet to vnet does not 10.1.2.5 configured so the inbound explanation at the bottom of the config will be better if "10.1.2.5" would exist in the sample

**Comment by KrisNey-MSFT** [comment]
Update to document needed, @KrisNey-MSFT to take a look

**Comment by KrisNey-MSFT** [comment]
Asking Kumaresh or Riff to take a look please...

**Comment by KrisNey-MSFT** [comment]
This Issue is saying it would be nice to have an Example to go along with this description in the HLD Section 3.6.1 VNET to VNET example and description.

![image](https://github.com/sonic-net/DASH/assets/22226040/2a19c23b-ecd5-43a3-b871-7b50bb6018b6)

**Comment by kperumalbfn** [comment]
@mgheorghe This is inbound lookup where ROUTE_RULE_TABLE match is based on the ENI+VNI and optional Source  PA prefix. In this example, inbound packet will match Source PA IP(101.1.2.3) and VNI(45654) in the ROUTE_RULE_TABLE entries to derive the 'decap' action and vnet 'vnet1'.

https://github.com/sonic-net/DASH/blob/main/documentation/general/dash-sonic-hld.md#329-route-rule-table---inbound

**Comment by r12f** [comment]
From DASH config above, the IP put there is not right and I have made a PR to fix it: https://github.com/sonic-net/DASH/pull/459.

**Comment by KrisNey-MSFT** [comment]
Fix above to be reviewed by @mgheorghe, then this can possibly be closed.  Will check during Community call, if not before.

**Comment by KrisNey-MSFT** [comment]
Fixed and merged
