### ISSUE TITLE
DASH_ROUTE_TABLE:{{eni}}:{{prefix}}  , eni should be "eni" should be more descriptive

### ISSUE THREAD

**Issue by mgheorghe** [sonic-net/DASH#454]
https://github.com/sonic-net/DASH/blob/main/documentation/general/dash-sonic-hld.md
```
DASH_ROUTE_TABLE:{{eni}}:{{prefix}}

    {
        "DASH_ROUTE_TABLE:F4939FEFC47E:10.2.5.0/24": {
            "action_type":"drop"
        },
        "OP": "SET"
    },
```

i see the ENI is mentioned as the MAC without separator, will be better if it is the eni_id, will be much easier to identify and see what it 
or if we want to keep "F4939FEFC47E" we shoudl update teh HLD to specify is the eni_mac_address

`DASH_ROUTE_TABLE:{{eni_mac_address}}:{{prefix}}`

or 

`DASH_ROUTE_TABLE:{{eni_id}}:{{prefix}}`

will make it more clear what value goes there

**Comment by KrisNey-MSFT** [comment]
Cancelling as this was a misunderstanding per @mgheorghe
