### ISSUE TITLE
Missing documentation for vnet peering and PL, ST

### ISSUE THREAD

**Issue by albgonzpri** [sonic-net/DASH#490]
The following links exist but do not have any documentation.
Are they work-in-progress? placeholders?

Thanks

1) vnet peering
[https://github.com/sonic-net/DASH/blob/main/documentation/vnet-peering-service/README.md](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsonic-net%2FDASH%2Fblob%2Fmain%2Fdocumentation%2Fvnet-peering-service%2FREADME.md&data=05%7C02%7CAlberto.Gonzalez%40microsoft.com%7C041f860bcbb34764ebb708dc019201c7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638386973809115639%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=navCR7J9LZRoD8ZtiL1OBt%2BQANdHoPZCisM8d%2Boc9jU%3D&reserved=0)
2) pl,st
[https://github.com/sonic-net/DASH/blob/main/documentation/stpl-service/README.md](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsonic-net%2FDASH%2Fblob%2Fmain%2Fdocumentation%2Fstpl-service%2FREADME.md&data=05%7C02%7CAlberto.Gonzalez%40microsoft.com%7C041f860bcbb34764ebb708dc019201c7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638386973809122513%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JV8h7yxOXrDCJQKZe3kXAXox6ZmB8eHwvlIVBGLl4yM%3D&reserved=0)

**Comment by KrisNey-MSFT** [comment]
Hi @albgonzpri , we do have documentation in the dash-sonic-hld (high level design)

Would you want to read it here?  [dash-sonic-hld](https://github.com/sonic-net/DASH/blob/main/documentation/general/dash-sonic-hld.md#23-service-tunnel-st-and-private-link-pl-packet-processing-pipelines)
