### ISSUE TITLE
sai challenger git commit issue

### ISSUE THREAD

**Issue by mgheorghe** [sonic-net/DASH#580]
"This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."
https://github.com/sonic-net/DASH/tree/main/test

**Comment by mgheorghe** [comment]
click on the sai-challenger link in test-cases

![image](https://github.com/sonic-net/DASH/assets/32941360/f2dff3e5-f5f2-46f4-a1f9-1b47c989dcc6)

**Comment by KrisNey-MSFT** [comment]
@mgheorghe agreed to check this out

**Comment by mgheorghe** [comment]
issue is still there

**Comment by KrisNey-MSFT** [comment]
hi @mgheorghe - would you be able to check on this one by chance?

**Comment by KrisNey-MSFT** [comment]
Just checking in @mgheorghe

**Comment by mgheorghe** [comment]
works now
