### ISSUE TITLE
what is the max scale supported by BMv2?

### ISSUE THREAD

**Issue by mgheorghe** [sonic-net/DASH#582]
i thought BMv2 is a software solution and there is a limitation only on the memory amount i have in my PC

but when trying to load 240K mappings i got

Error when trying to add entry to table 'dash_ingress.outbound.outbound_mapping_stage.ca_to_pa': TABLE_FULL

it loaded ~1000 mapping or so before it failed

**Comment by r12f** [comment]
Hi Mircea, yea, although BMv2 is a software implementation, but it is not designed for handling large scale of objects or traffic. By default the table size in BMv2 is set to 1024. This limit can be found in the bmv2 backend in p4c repo.

Here is the screenshot of the key code, for your convenience:

![image](https://github.com/sonic-net/DASH/assets/1533278/bcea74e8-24ac-4bf6-925b-e42fbe548b26)

**Comment by mgheorghe** [comment]
see also https://github.com/sonic-net/DASH/pull/644
