### ISSUE TITLE
Compare OpenContrail to Pensando model for flow tracking, TCP State Machine

### ISSUE THREAD

**Issue by KrisNey-MSFT** [sonic-net/DASH#81]
## Related information

We (as a team) need to make a decision re: the model to use, then we can resolve the PR and Issue below.  Ideally we make sure all xn tracking cases are covered.  

### Related work items

- [x] PR: [PNA compatible connection tracking #21](https://github.com/Azure/DASH/pull/21)
- [ ] Issue: [Connection Tracking: Too loose, UDP and Aging #10e](https://github.com/Azure/DASH/issues/10)

**Comment by KrisNey-MSFT** [comment]
From the call today it was agreed to leverage the OpenContrail information into the DASH behavioral model.

**Comment by KrisNey-MSFT** [comment]
As far as the task Mario is working on (implementing proper connection tracking behavior)

**Comment by KrisNey-MSFT** [comment]
Transferring to Vijay, Sanjay, etc...
**To do**:  raise PR for SAI headers and bmv2 and metering
APP_DB end of August.

**Comment by KrisNey-MSFT** [comment]
Contrail model/code takes care of connection addition and removal, handling timers (not actual xn tracking while it is open).  
XN learning for Stateful ACL

**Comment by KrisNey-MSFT** [comment]
Existing programs not in line w/PNA; proposed to PNA to add / remove entries (add-entry-if and set-exprire-time)
Desire from PNA community to convert tuple of fields into boolean condition 
Has been accepted into PNA
Rudimentary ACL tracking works (NVidia)
Compiles in P4 C, does not work in bmv2 - does not like expression-type boolean

Use Registers or modifiable Table Entries (Mario)?  Are we bound to PNA?  Can we take our own direction?  

Gerald Degrace
TCP state machine, Connection Tracking, Re-simulation, aging, HA have to be considered up front as these functions interact with the connection table

And we need to be able to monitor the TCP state machine for debugging

And to be able to read any connection out for debugging as well

TCP visibility may possibly only be used in functional testing if it affects performance

**Comment by KrisNey-MSFT** [comment]
4 tables in pipeline: Conn_track in and out direction lookups creating 4 tables instead of 2
Connection tracking code not compiling today in P4 (could be table placement in stages conflict?)
Need a way to tell the compiler it is the same table
With ACL, copies are pushed out to all of the tables.  Are we doing the same thing here?
In spec, if you apply tables more than once, entries need to be kept up to date in all (can no longer rely on the control plane).
Should we try to write the code where it is 1 table instead?   Copies in datapath, or solve in pipeline?  (Real implementation needs to have multiple (2) tables).

**Comment by yusefMS06** [comment]
@marian-pritsak Circling back to this.. is this issue still blocked?

**Comment by KrisNey-MSFT** [comment]
This will be superceded by incoming Flow API to provide a vendor neutral API carrying the flow states for debugging. K to close
